openapi: 3.0.0
info:
  title: oneleif API
  version: 0.2.0
  description: |
    API documentation of oneleif backend.

    You can find this project [here on GitHub](https://github.com/oneleif/olWebsite).

    Find out more on our [Discord](https://discordapp.com/invite/tv9UdJK) server.
  x-logo:
    url: ../logo.png
    altText: oneleif logo

servers:
  - url: https://dev.api.oneleif.com/api
    description: Staging server
  - url: https://api.oneleif.com/api
    description: Main (production) server

paths:
  # user controller
  /register:
    post:
      tags:
        - User
      summary: Register user
      description: Registers new user in the system
      operationId: register
      requestBody:
        $ref: "#/components/requestBodies/RegisterUserRequestBody"
      responses:
        "201":
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          $ref: "#/components/responses/400BadRequest"
  /login:
    post:
      tags:
        - Authorization
      summary: Login user
      description: Authenticates the user and creates new session
      operationId: login
      requestBody:
        $ref: "#/components/requestBodies/LoginRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/LoginSuccessful"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        default:
          $ref: "#/components/responses/GenericError"
  /refresh-token:
    post:
      tags:
        - Authorization
      summary: Refreshes token
      description: Authenticates the user and creates new session
      operationId: refreshToken
      requestBody:
        $ref: "#/components/requestBodies/RefreshTokenRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/RefreshTokenSuccessful"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "400":
          $ref: "#/components/responses/400BadRequest"
        default:
          $ref: "#/components/responses/GenericError"
  /logout:
    get:
      security:
        - bearerAuth: []
      tags:
        - Authorization
      summary: Logout user
      description: Ends user session by invalidating tokens (provided access token and associated refresh token)
      operationId: logout
      responses:
        "204":
          description: User successfully logged out
        default:
          $ref: "#/components/responses/GenericError"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: number
          readOnly: true
        email:
          type: string
        password:
          type: string
          writeOnly: true
        social:
          $ref: "#/components/schemas/SocialInformation"
          readOnly: true

    SocialInformation:
      title: Social Information
      type: object
      properties:
        id:
          type: number
          readOnly: true
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        discordUsername:
          type: string
        githubUsername:
          type: string
        tags:
          type: array
          items:
            type: string
        profileImage:
          type: string
        biography:
          type: string
        links:
          type: array
          items:
            type: string
        location:
          type: string

    AccessToken:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        error:
          type: boolean
        reason:
          type: string

    LoginResponse:
      type: object
      properties:
        token:
          $ref: "#/components/schemas/AccessToken"
        user:
          $ref: "#/components/schemas/User"

  requestBodies:
    RegisterUserRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string

    LoginRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string

    RefreshTokenRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              refreshToken:
                type: string

  responses:
    LoginSuccessful:
      description: User successfully logged in
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/LoginResponse"
    RefreshTokenSuccessful:
      description: Token successfully refreshed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AccessToken"
    400BadRequest:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    401Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    GenericError:
      description: Something went wrong
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Bearer
