version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  test:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  test-release:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Compile code with optimizations
          command: swift build -c release

  build-and-deploy-image:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker release image
          command: |
            docker build -t oneleif-api:latest -f web.Dockerfile --build-arg env=production  .
            docker tag oneleif-api:latest oneleif-api:$CIRCLE_SHA1
      - run:
          name: Create image archives
          command: |
            docker save oneleif-api:latest | gzip > oneleif-api.latest.tar.gz
            docker save oneleif-api:$CIRCLE_SHA1 | gzip > oneleif-api.$CIRCLE_SHA1.tar.gz
            mkdir -p images && mv oneleif-api.*.tar.gz images/
      - aws-s3/sync:
          from: images
          to: $S3_DOCKER_IMAGES_BUCKET_URL/production
          overwrite: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - test-release
      - build-and-deploy-image:
          requires:
            - test
            - test-release
